<?php
$bizkickhalloweenHelper = $this->helper('Hiddentechies\BizkickHalloween\Helper\Data');
$enablePromotion = $bizkickhalloweenHelper->getConfigValue('bizkickhalloweensettings/promotion_settings/enable_promotion');
$promotionText = $bizkickhalloweenHelper->getConfigValue('bizkickhalloweensettings/promotion_settings/promotion_text');
?>
<?php if ($enablePromotion == 1) { ?>
    <?php if ($promotionText != '') { ?>
        <div class="promotion-wrapper">
            <div class="page-main">
                <?php echo $promotionText; ?>
            </div>
        </div>
    <?php } ?>
<?php } ?>